# Example configuration for the webserver
# at https://github.com/monopole/hello
commonLabels:
  app: nginx
resources:
- Deployment.yaml
- services.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: nginx
  newTag: "1.18"
namespace: default
