# Example configuration for the webserver
# at https://github.com/monopole/hello
resources:
- deployment.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.cn-east-3.myhuaweicloud.com/lemon-develop/xxljob_admin
  newTag: v20240110215418
namespace: xxl-job
