# Example configuration for the webserver
# at https://github.com/monopole/hello
commonLabels:
  app: id-server-production
resources:
- id-server-deployment.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.cn-east-3.myhuaweicloud.com/hwy-test/my-id-server
  newTag: 0.0.1-202401051704
namespace: hwtest-node-dx
